on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - uses: ros-tooling/setup-ros@v0.6
      - uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: jazzy
          package-name: kortex_bringup kortex_driver
